---
env: "{{ lookup('env', 'ENVIRONMENT') | default('dev', true) }}"
aws_region: ap-southeast-1
ecr_repository_prefix: cicd-sample
release_sha: "{{ lookup('env', 'RELEASE_SHA') }}"
ecr_registry: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
apache_image: "{{ ecr_registry }}/{{ ecr_repository_prefix }}/apache:{{ release_sha }}"
tomcat_image: "{{ ecr_registry }}/{{ ecr_repository_prefix }}/tomcat:{{ release_sha }}"
rtcm_ssm_path: /cicd/rtcm/approved/current
deployment_decision_prefix: /cicd/deployment-decisions
datadog_api_key_ssm: /cicd/datadog/api-key
datadog_enabled: true
container_run_as_root: false
container_read_only_rootfs: true
container_drop_all_caps: true
app_data_mount_enabled: true
app_mount_config_ssm_path: "/{{ env }}/app/storage/mount-config"
app_data_volume_id_ssm_path: "/{{ env }}/app/storage/app-data-volume-id"
app_data_volume_id: "{{ lookup('env', 'APP_DATA_VOLUME_ID') | default('', true) }}"
app_mount_read_from_ssm: true
app_mount_point: /webserver
app_filesystem_type: xfs
app_filesystem_label: WEBAPPDATA
app_data_allow_format: true
