[apache]
# EC2 instances running the Apache httpd container in dev.
# Populated dynamically by the CI/CD pipeline using aws_ec2 plugin.

[tomcat]
# EC2 instances running the Tomcat container in dev.

[app:children]
apache
tomcat
