---
galaxy_info:
  role_name: storage_mount
  author: app-as-code
  description: Manage mandatory secondary application data volume mount by UUID.
  license: MIT
  min_ansible_version: "2.14"
dependencies: []
